var song2Data = {
    "tempo": 70,
    "voices": [
        {
            "waveform": "triangle",
            "volume": 0.15,
            "seq": [
                [
                    "B2",
                    8,
                    true
                ],
                [
                    "A2",
                    8,
                    true
                ],
                [
                    "F2",
                    8,
                    true
                ],
                [
                    "D2",
                    8,
                    true
                ],
                [
                    "B2",
                    8,
                    true
                ],
                [
                    "A2",
                    8,
                    true
                ],
                [
                    "F2",
                    8,
                    true
                ],
                [
                    "D2",
                    8,
                    true
                ],
                [
                    "G2",
                    8,
                    true
                ],
                [
                    "D2",
                    8,
                    true
                ],
                [
                    "A#2",
                    8,
                    true
                ],
                [
                    "A2",
                    8,
                    true
                ],
                [
                    "B2",
                    8,
                    true
                ],
                [
                    "A2",
                    8,
                    true
                ],
                [
                    "F2",
                    8,
                    true
                ],
                [
                    "D2",
                    8,
                    true
                ],
                [
                    "B2",
                    8,
                    true
                ],
                [
                    "A2",
                    8,
                    true
                ],
                [
                    "F2",
                    8,
                    true
                ],
                [
                    "D2",
                    8,
                    true
                ],
                [
                    "G2",
                    8,
                    true
                ],
                [
                    "D2",
                    8,
                    true
                ],
                [
                    "A2",
                    8,
                    true
                ],
                [
                    "F#2",
                    8,
                    true
                ]
            ]
        },
        {
            "waveform": "triangle",
            "volume": 0.15,
            "seq": [
                [
                    "r",
                    2,
                    true
                ],
                [
                    "D3",
                    2,
                    true
                ],
                [
                    "r",
                    2
                ],
                [
                    "F#3",
                    2,
                    true
                ],
                [
                    "r",
                    2
                ],
                [
                    "E3",
                    2,
                    true
                ],
                [
                    "r",
                    2
                ],
                [
                    "G3",
                    2,
                    true
                ],
                [
                    "r",
                    2
                ],
                [
                    "A3",
                    2,
                    true
                ],
                [
                    "r",
                    2
                ],
                [
                    "C3",
                    2,
                    true
                ],
                [
                    "r",
                    2
                ],
                [
                    "F#3",
                    2,
                    true
                ],
                [
                    "r",
                    2
                ],
                [
                    "A3",
                    2,
                    true
                ],
                [
                    "r",
                    2,
                    true
                ],
                [
                    "D3",
                    2,
                    true
                ],
                [
                    "r",
                    2
                ],
                [
                    "F#3",
                    2,
                    true
                ],
                [
                    "r",
                    2
                ],
                [
                    "E3",
                    2,
                    true
                ],
                [
                    "r",
                    2
                ],
                [
                    "G3",
                    2,
                    true
                ],
                [
                    "r",
                    2
                ],
                [
                    "A3",
                    2,
                    true
                ],
                [
                    "r",
                    2
                ],
                [
                    "C3",
                    2,
                    true
                ],
                [
                    "r",
                    2
                ],
                [
                    "F#3",
                    2,
                    true
                ],
                [
                    "r",
                    2
                ],
                [
                    "A3",
                    2,
                    true
                ],
                [
                    "r",
                    2
                ],
                [
                    "A#3",
                    2,
                    true
                ],
                [
                    "r",
                    2
                ],
                [
                    "D3",
                    2,
                    true
                ],
                [
                    "r",
                    2
                ],
                [
                    "F3",
                    2,
                    true
                ],
                [
                    "r",
                    2
                ],
                [
                    "A3",
                    2,
                    true
                ],
                [
                    "r",
                    2
                ],
                [
                    "D3",
                    2,
                    true
                ],
                [
                    "r",
                    2
                ],
                [
                    "E3",
                    2,
                    true
                ],
                [
                    "r",
                    2
                ],
                [
                    "C#3",
                    2,
                    true
                ],
                [
                    "r",
                    2
                ],
                [
                    "D3",
                    2,
                    true
                ],
                [
                    "r",
                    2,
                    true
                ],
                [
                    "D3",
                    2,
                    true
                ],
                [
                    "r",
                    2
                ],
                [
                    "F#3",
                    2,
                    true
                ],
                [
                    "r",
                    2
                ],
                [
                    "E3",
                    2,
                    true
                ],
                [
                    "r",
                    2
                ],
                [
                    "G3",
                    2,
                    true
                ],
                [
                    "r",
                    2
                ],
                [
                    "A3",
                    2,
                    true
                ],
                [
                    "r",
                    2
                ],
                [
                    "C3",
                    2,
                    true
                ],
                [
                    "r",
                    2
                ],
                [
                    "F#3",
                    2,
                    true
                ],
                [
                    "r",
                    2
                ],
                [
                    "A3",
                    2,
                    true
                ],
                [
                    "r",
                    2,
                    true
                ],
                [
                    "D3",
                    2,
                    true
                ],
                [
                    "r",
                    2
                ],
                [
                    "F#3",
                    2,
                    true
                ],
                [
                    "r",
                    2
                ],
                [
                    "E3",
                    2,
                    true
                ],
                [
                    "r",
                    2
                ],
                [
                    "G3",
                    2,
                    true
                ],
                [
                    "r",
                    2
                ],
                [
                    "A3",
                    2,
                    true
                ],
                [
                    "r",
                    2
                ],
                [
                    "C3",
                    2,
                    true
                ],
                [
                    "r",
                    2
                ],
                [
                    "F#3",
                    2,
                    true
                ],
                [
                    "r",
                    2
                ],
                [
                    "A3",
                    2,
                    true
                ],
                [
                    "r",
                    2
                ],
                [
                    "B3",
                    2,
                    true
                ],
                [
                    "r",
                    2
                ],
                [
                    "D3",
                    2,
                    true
                ],
                [
                    "r",
                    2
                ],
                [
                    "F#3",
                    2,
                    true
                ],
                [
                    "r",
                    2
                ],
                [
                    "A3",
                    2,
                    true
                ],
                [
                    "r",
                    2
                ],
                [
                    "C#3",
                    2,
                    true
                ],
                [
                    "r",
                    2
                ],
                [
                    "E3",
                    2,
                    true
                ],
                [
                    "r",
                    2
                ],
                [
                    "A#3",
                    2,
                    true
                ],
                [
                    "r",
                    2
                ],
                [
                    "C#3",
                    2,
                    true
                ]
            ]
        }
    ],
    "notes": "A: Bm - A7 - F - D\nB1: G-mol - Dm - Bb-dur - A7\nB2: G-dur - D-dur - A-dur - F#7"
};
